title: 涅槃之道
description: 心有多远，路就有多远。

url: http://blog.halo9pan.cn
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
redcarpet:
    extensions: ["tables"]
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about.html
 - title: 联系
   url: /contact.html

social:
   github: Halo9Pan
   twitter: Halo9Pan
   facebook: Halo9Pan
   email: me@halo9pan.cn

google_analytics: "UA-43856748-6"
